### ISSUE TITLE
發現一個BUG

### ISSUE THREAD

**Issue by avatarANDY** [qingfeng346/Scorpio-CSharp#1]
作者你好
最近, 在最新v1.0.3版本中發現一個BUG

v1.0.0 第一个发行版不會有此BUG

Main = 
{
TestValue = 0;
	
	function OnAwake()
	{
		Debug.Log( "#1 TestValue= " + this.TestValue );
		var i = this.TestValue;            // 這裡應該要是賦值，但卻變成參考
		++i;                               // 導致 ++i 變成了加到 this.TestValue
		Debug.Log( "#2 TestValue= " + this.TestValue );
	}
}

謝謝 ^_^

**Comment by qingfeng346** [comment]
好的，正在处理，多谢反馈

**Comment by qingfeng346** [comment]
已于 v1.0.5  版本修复
