### ISSUE TITLE
Unity 2018.3.6f1 (64-bit) - IL2CPP 問題

### ISSUE THREAD

**Issue by avatarANDY** [qingfeng346/Scorpio-CSharp#2]
作者你好, 我又來了...
我使用 Unity 2018.3.6f1 (64-bit), 設定用  IL2CPP 來輸出 android - apk
跑 Scorpio-CSharp 會有一些問題
1. 腳本一開始若使用 Application.version 會是 null, 若繼續執行就觸發例外訊息
2. 腳本繼續跑下去, 就馬上會出現死機的狀況, 畫面整個卡死了
我調查原因是腳本去呼叫c#功能, 要讀取AssetBundle, 卡死在LoadAsset裡面... 
但我用c#呼叫時又不會發生卡死...
不知原因為何

PS: 同樣的code, 若使用預設的Mono就一切正常
對了～非常感謝有這麼好用的 Scorpio-CSharp, 很棒,  ^_^

**Comment by qingfeng346** [comment]
这个问题你可以加一下QQ群 245199668 ，我是群主，直接私我，方便的话 我需要看一下代码，看你的描述 感觉像是unity的BUG。

**Comment by avatarANDY** [comment]
那...我整理一個新專案來測試看看能否重現BUG... 這樣比較好釐清問題點... 在跟你聯繫   :D

**Comment by qingfeng346** [comment]
好

**Comment by qingfeng346** [comment]
> 
> 
> 那...我整理一個新專案來測試看看能否重現BUG... 這樣比較好釐清問題點... 在跟你聯繫 :D

好

**Comment by avatarANDY** [comment]
經過我非常仔細的拆解測試... 

使用 IL2CPP 在編輯器內測試都正常, 輸出apk到手機執行, 就會crash的問題
確實是unity的bug.
就是當產生一個 Sphere 物件時，就會crash，是整個畫面卡死了
經過拆解，是sphere collider造成的影響，把他換成box collider就一切正常了
--------------------
不過, Scorpio-CSharp 也確實有一點點問題
就是使用 Application.version 就一樣是null 而無法在腳本中使用了

謝謝 :D

**Comment by qingfeng346** [comment]
@avatarANDY 
application.version   是il2cpp的问题，这个问题在readme里有写。这个需要你重新包一层或者使用去反射功能


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by avatarANDY** [comment]
原來如此...非常感謝回覆 ^_^

**Comment by avatarANDY** [comment]
原來如此... 非常感謝回覆 ^_^
